import { copyFileSync, existsSync, mkdirSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { getExampleAppsDir, getProfileExampleAppsDir } from "./paths.js";
import { createLogger } from "./logger.js";

const log = createLogger("profile-example-apps");

/**
 * Build-output / dependency / VCS dirs that must never be seeded into the
 * guardian's authoring copy — they are regenerated by `pnpm install` + `rome
 * build` when the guardian first builds the starter, and copying them would
 * drag stale, workspace-linked artifacts into a standalone app.
 */
const SKIP_ENTRIES = new Set(["node_modules", "dist", ".git", ".rome", ".turbo", ".DS_Store"]);

function copyTreeExcluding(sourceDir: string, destDir: string): void {
  mkdirSync(destDir, { recursive: true });
  for (const entry of readdirSync(sourceDir, { withFileTypes: true })) {
    if (SKIP_ENTRIES.has(entry.name)) continue;
    const sourcePath = join(sourceDir, entry.name);
    const destPath = join(destDir, entry.name);
    if (entry.isDirectory()) {
      copyTreeExcluding(sourcePath, destPath);
    } else if (entry.isFile()) {
      copyFileSync(sourcePath, destPath);
    }
  }
}

/** An example app source dir is one that carries an `app.yaml`. */
function discoverExampleApps(exampleAppsDir: string): string[] {
  if (!existsSync(exampleAppsDir)) return [];
  const ids: string[] = [];
  for (const entry of readdirSync(exampleAppsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (existsSync(join(exampleAppsDir, entry.name, "app.yaml"))) {
      ids.push(entry.name);
    }
  }
  return ids;
}

/**
 * Seed the example/reference apps into the per-profile example-apps directory
 * (`~/.rome/<profile>/projects/example-apps/<appId>`) as **editable starters** —
 * kept separate from the guardian's own authoring dir (`projects/apps`).
 *
 * Directory-level copy-if-missing: an example is seeded only when its
 * destination does not yet exist, so this never clobbers a guardian's edits and
 * is safe to run on every boot. The apps are NOT installed — they sit as plain,
 * editable source the guardian can open, build, and install via the normal
 * app-creation flow (which `git init`s on build, so we ship no `.git` here).
 *
 * No-ops gracefully when the example source is absent (e.g. a layout where
 * `example_apps/` was not shipped), matching `ensureProfileMemoryInitialized`'s
 * existsSync-guarded seeding.
 */
export function ensureProfileExampleAppsSeeded(): readonly string[] {
  const exampleAppsDir = getExampleAppsDir();
  const destRoot = getProfileExampleAppsDir();

  const appIds = discoverExampleApps(exampleAppsDir);
  if (appIds.length === 0) return [];

  const seeded: string[] = [];
  for (const appId of appIds) {
    const dest = join(destRoot, appId);
    if (existsSync(dest)) continue;

    const source = join(exampleAppsDir, appId);
    if (!statSync(source).isDirectory()) continue;

    try {
      copyTreeExcluding(source, dest);
      seeded.push(appId);
    } catch (error) {
      log.warn("failed to seed example app", {
        appId,
        error: error instanceof Error ? error.message : String(error),
      });
    }
  }

  if (seeded.length > 0) {
    log.info("seeded example apps", { seeded, destRoot });
  }
  return seeded;
}
