import { Ajv2020, type ErrorObject, type ValidateFunction } from "ajv/dist/2020.js";
import type { ActionArgSchema, ActionInputSchema } from "@/hooks/use-action-catalog";

/** One problem found by `validateArgsAgainstSchema`, keyed so the caller can
 * map it onto a translated message. */
export type ArgsIssue =
  | { kind: "missing"; name: string }
  | { kind: "type"; name: string; expected: string }
  | { kind: "unknown"; name: string }
  | { kind: "schema"; path: string; message: string };

export type ArgsEvaluation =
  | { kind: "invalid-json" }
  | { kind: "not-object" }
  | { kind: "unvalidated"; args: Record<string, unknown> }
  | { kind: "invalid"; args: Record<string, unknown>; issues: ArgsIssue[] }
  | { kind: "valid"; args: Record<string, unknown> };

// Action schemas are generated by Zod 4, whose native JSON Schema target is
// draft 2020-12. Use the matching Ajv build so newer keywords such as
// `prefixItems` are validated rather than silently treated as annotations.
const ajv = new Ajv2020({ allErrors: true, strict: false });
const validators = new WeakMap<ActionInputSchema, ValidateFunction>();

function schemaTypes(prop: ActionArgSchema): string[] {
  if (Array.isArray(prop.type)) {
    return prop.type.filter((t): t is string => typeof t === "string");
  }
  return typeof prop.type === "string" ? [prop.type] : [];
}

function placeholderFor(prop: ActionArgSchema): unknown {
  if (prop.default !== undefined) return prop.default;
  if (Array.isArray(prop.enum) && prop.enum.length > 0) return prop.enum[0];
  switch (schemaTypes(prop)[0]) {
    case "number":
    case "integer":
      return 0;
    case "boolean":
      return false;
    case "array":
      return [];
    case "object":
      return {};
    default:
      return "";
  }
}

/** Build starter args for an action: every required property with a
 * placeholder value (schema default, first enum value, or the type's zero
 * value). Pretty-printed so it drops straight into the args textarea. */
export function buildArgsTemplate(schema: ActionInputSchema | null | undefined): string {
  const properties = schema?.properties ?? {};
  const template: Record<string, unknown> = {};
  for (const name of schema?.required ?? []) {
    template[name] = name in properties ? placeholderFor(properties[name]) : "";
  }
  if (Object.keys(template).length === 0) return "{}";
  return JSON.stringify(template, null, 2);
}

function validatorFor(schema: ActionInputSchema): ValidateFunction {
  const cached = validators.get(schema);
  if (cached) return cached;
  const validator = ajv.compile(schema);
  validators.set(schema, validator);
  return validator;
}

function pointerToPath(pointer: string): string {
  if (!pointer) return "";
  return pointer
    .split("/")
    .slice(1)
    .map((segment) => segment.replaceAll("~1", "/").replaceAll("~0", "~"))
    .join(".");
}

function childPath(pointer: string, child: unknown): string {
  const parent = pointerToPath(pointer);
  const name = typeof child === "string" ? child : "";
  return [parent, name].filter(Boolean).join(".");
}

function projectSchemaError(error: ErrorObject): ArgsIssue {
  if (error.keyword === "required") {
    return {
      kind: "missing",
      name: childPath(error.instancePath, error.params.missingProperty),
    };
  }
  if (error.keyword === "type") {
    const expected = error.params.type;
    return {
      kind: "type",
      name: pointerToPath(error.instancePath) || "args",
      expected: Array.isArray(expected) ? expected.join(" | ") : String(expected),
    };
  }
  if (error.keyword === "additionalProperties") {
    return {
      kind: "unknown",
      name: childPath(error.instancePath, error.params.additionalProperty),
    };
  }
  return {
    kind: "schema",
    path: pointerToPath(error.instancePath) || "args",
    message: error.message ?? `failed ${error.keyword}`,
  };
}

/** Validate parsed args against the action's complete JSON Schema. Ajv covers
 * composed and value constraints (`enum`, `allOf`, `if`/`then`, nested
 * `required`, and so on), so an empty issue list is authoritative. */
export function validateArgsAgainstSchema(
  args: Record<string, unknown>,
  schema: ActionInputSchema,
): ArgsIssue[] {
  let validator: ValidateFunction;
  try {
    validator = validatorFor(schema);
  } catch (error) {
    return [
      {
        kind: "schema",
        path: "args",
        message: `schema could not be evaluated: ${
          error instanceof Error ? error.message : String(error)
        }`,
      },
    ];
  }

  return validator(args) ? [] : (validator.errors ?? []).map(projectSchemaError);
}

/** Parse textarea input once and return the same validation result used by
 * both form submission and the positive-validity indicator. */
export function evaluateArgsText(
  text: string,
  schema: ActionInputSchema | null | undefined,
): ArgsEvaluation {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return { kind: "invalid-json" };
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    return { kind: "not-object" };
  }

  const args = parsed as Record<string, unknown>;
  if (!schema) return { kind: "unvalidated", args };
  const issues = validateArgsAgainstSchema(args, schema);
  return issues.length > 0 ? { kind: "invalid", args, issues } : { kind: "valid", args };
}

/** Human-readable type label ("string", "number | string") for the args help
 * panel. */
export function describeArgType(prop: ActionArgSchema): string {
  const types = schemaTypes(prop);
  return types.length > 0 ? types.join(" | ") : "any";
}
