#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Rome — Setup Script (non-interactive)
# Downloads and configures Rome from Docker Hub (no git clone needed).
# All configuration is read from environment variables.
# Required: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN
# Optional: ANTHROPIC_API_KEY, ROME_JWT_SECRET,
#           SSH_USER_PASSWORD, TS_HOSTNAME, ROME_DIR, WEB_PORT,
#           ROME_DOCKER_USER_MODE
# Usage: DOCKERHUB_USERNAME=x DOCKERHUB_TOKEN=y bash <(curl -fsSL https://raw.githubusercontent.com/yunfanye/rome/main/scripts/setup.sh)
# =============================================================================

ROME_IMAGE="yunfanye/rome:latest"
ROME_DIR="${ROME_DIR:-$HOME/rome}"

# ─── Helpers ─────────────────────────────────────────────────────────────────

info() { printf '\033[1;34m[info]\033[0m  %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m  %s\n' "$*"; }
error() {
  printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2
  exit 1
}

# Source .env if it exists (allows setting variables there instead of exporting)
if [ -f .env ]; then
  set -a
  # shellcheck source=/dev/null
  source .env
  set +a
  info "Loaded configuration from .env"
fi

generate_secret() {
  openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64
}

# ─── Prerequisites ───────────────────────────────────────────────────────────

check_prerequisites() {
  if ! command -v docker &>/dev/null; then
    error "Docker is not installed. Please install Docker first: https://docs.docker.com/get-docker/"
  fi

  if ! docker compose version &>/dev/null; then
    error "Docker Compose is not available. Please install Docker Compose: https://docs.docker.com/compose/install/"
  fi

  if ! docker info &>/dev/null 2>&1; then
    error "Docker daemon is not running. Please start Docker and try again."
  fi

  info "Prerequisites OK (Docker + Docker Compose)"
}

# ─── Collect configuration ───────────────────────────────────────────────────
# All values are read from environment variables (set them before running, or
# source a .env file).  Only DOCKERHUB_USERNAME and DOCKERHUB_TOKEN are required.

collect_config() {
  info "Setting up Rome in: $ROME_DIR"

  # Anthropic API key (optional)
  ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
  if [ -n "$ANTHROPIC_API_KEY" ]; then
    info "ANTHROPIC_API_KEY provided"
  else
    warn "ANTHROPIC_API_KEY not set — you can add it to .env later"
  fi

  # JWT secret — auto-generate if not provided
  ROME_JWT_SECRET="${ROME_JWT_SECRET:-$(generate_secret)}"

  # Docker Hub (required — private image)
  DOCKERHUB_USERNAME="${DOCKERHUB_USERNAME:-}"
  DOCKERHUB_TOKEN="${DOCKERHUB_TOKEN:-}"
  if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_TOKEN" ]; then
    error "Docker Hub credentials are required. Set DOCKERHUB_USERNAME and DOCKERHUB_TOKEN environment variables."
  fi
  info "Docker Hub credentials found (user: $DOCKERHUB_USERNAME)"

  # Optional
  SSH_USER_PASSWORD="${SSH_USER_PASSWORD:-}"
  TS_HOSTNAME="${TS_HOSTNAME:-}"
  WEB_PORT="${WEB_PORT:-3000}"
  ROME_DOCKER_USER_MODE="${ROME_DOCKER_USER_MODE:-multi}"
}

# ─── Generate files ──────────────────────────────────────────────────────────

generate_env() {
  local env_file="$ROME_DIR/.env"
  info "Generating $env_file"

  cat >"$env_file" <<EOF
# Rome — generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Web dashboard
ROME_JWT_SECRET=$ROME_JWT_SECRET
EOF

  if [ -n "$ANTHROPIC_API_KEY" ]; then
    echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >>"$env_file"
  fi

  if [ -n "$SSH_USER_PASSWORD" ]; then
    echo "SSH_USER_PASSWORD=$SSH_USER_PASSWORD" >>"$env_file"
  fi

  # Docker Hub credentials (for future pulls)
  cat >>"$env_file" <<EOF

# Docker Hub (private image)
DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
DOCKERHUB_TOKEN=$DOCKERHUB_TOKEN
EOF
}

generate_compose() {
  local compose_file="$ROME_DIR/docker-compose.yml"
  info "Generating $compose_file"

  local ts_hostname="${TS_HOSTNAME:-rome}"

  cat >"$compose_file" <<EOF
services:
  rome:
    image: $ROME_IMAGE
    ports:
      - "$WEB_PORT:3000"
    volumes:
      - app:/app
      - $ROME_DIR/home/user:/home/user
      - rome-home:/home/rome
      - $ROME_DIR/ssh-host-keys:/etc/ssh/ssh_host_keys
      - $ROME_DIR/tailscale:/var/lib/tailscale
    env_file: .env
    environment:
      - NODE_ENV=production
      - WEB_HOST=0.0.0.0
      - TS_HOSTNAME=$ts_hostname
      - ROME_DOCKER_USER_MODE=$ROME_DOCKER_USER_MODE
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:4141/api/health').then(r=>{if(!r.ok)throw 1}).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  app:
  rome-home:
EOF
}

create_directories() {
  info "Creating directories"
  mkdir -p "$ROME_DIR/home/user"
  mkdir -p "$ROME_DIR/ssh-host-keys"
  mkdir -p "$ROME_DIR/tailscale"
}

# ─── Start ───────────────────────────────────────────────────────────────────

start_rome() {
  info "Logging in to Docker Hub ..."
  echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  info "Pulling image: $ROME_IMAGE"
  docker pull "$ROME_IMAGE"

  info "Starting Rome ..."
  cd "$ROME_DIR"
  docker compose up -d

  echo
  echo "=== Rome is starting! ==="
  echo
  echo "  Web dashboard:  http://localhost:$WEB_PORT"
  echo
  echo "  Project dir:    $ROME_DIR"
  echo
  echo "  Useful commands:"
  echo "    cd $ROME_DIR && docker compose logs -f    # View logs"
  echo "    cd $ROME_DIR && docker compose ps         # Check status"
  echo "    cd $ROME_DIR && docker compose down       # Stop"
  echo "    cd $ROME_DIR && docker compose pull       # Update image"
  echo
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
  check_prerequisites
  collect_config
  mkdir -p "$ROME_DIR"
  create_directories
  generate_env
  generate_compose
  start_rome
}

main "$@"
